title: GetFoodUSA VRS
email: getfoodusasocialmedia@gmail.com
description: >-
  A place to help get new aspiring volunteers up and running! 
baseurl: ""
url: ""

include: ['_pages']
markdown: kramdown
